name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run lint checker
        run: ./gradlew detekt
